//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	predictionv1alpha1 "github.com/gocrane-io/api/prediction/v1alpha1"
	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedHorizontalPodAutoscaler) DeepCopyInto(out *AdvancedHorizontalPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedHorizontalPodAutoscaler.
func (in *AdvancedHorizontalPodAutoscaler) DeepCopy() *AdvancedHorizontalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(AdvancedHorizontalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdvancedHorizontalPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedHorizontalPodAutoscalerList) DeepCopyInto(out *AdvancedHorizontalPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdvancedHorizontalPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedHorizontalPodAutoscalerList.
func (in *AdvancedHorizontalPodAutoscalerList) DeepCopy() *AdvancedHorizontalPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(AdvancedHorizontalPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdvancedHorizontalPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedHorizontalPodAutoscalerSpec) DeepCopyInto(out *AdvancedHorizontalPodAutoscalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.MinReplicaCount != nil {
		in, out := &in.MinReplicaCount, &out.MinReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2beta2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(v2beta2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
	in.PredictionConfig.DeepCopyInto(&out.PredictionConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedHorizontalPodAutoscalerSpec.
func (in *AdvancedHorizontalPodAutoscalerSpec) DeepCopy() *AdvancedHorizontalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(AdvancedHorizontalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedHorizontalPodAutoscalerStatus) DeepCopyInto(out *AdvancedHorizontalPodAutoscalerStatus) {
	*out = *in
	if in.ExpectReplicaCount != nil {
		in, out := &in.ExpectReplicaCount, &out.ExpectReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.CurrentReplicaCount != nil {
		in, out := &in.CurrentReplicaCount, &out.CurrentReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedHorizontalPodAutoscalerStatus.
func (in *AdvancedHorizontalPodAutoscalerStatus) DeepCopy() *AdvancedHorizontalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(AdvancedHorizontalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionAlgorithm) DeepCopyInto(out *PredictionAlgorithm) {
	*out = *in
	if in.DSP != nil {
		in, out := &in.DSP, &out.DSP
		*out = new(predictionv1alpha1.DspConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = new(predictionv1alpha1.PercentileConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionAlgorithm.
func (in *PredictionAlgorithm) DeepCopy() *PredictionAlgorithm {
	if in == nil {
		return nil
	}
	out := new(PredictionAlgorithm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionConfig) DeepCopyInto(out *PredictionConfig) {
	*out = *in
	if in.PredictionWindow != nil {
		in, out := &in.PredictionWindow, &out.PredictionWindow
		*out = new(int32)
		**out = **in
	}
	if in.PredictionAlgorithm != nil {
		in, out := &in.PredictionAlgorithm, &out.PredictionAlgorithm
		*out = new(PredictionAlgorithm)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionConfig.
func (in *PredictionConfig) DeepCopy() *PredictionConfig {
	if in == nil {
		return nil
	}
	out := new(PredictionConfig)
	in.DeepCopyInto(out)
	return out
}
