//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	predictionv1alpha1 "github.com/gocrane/api/prediction/v1alpha1"
	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveHorizontalPodAutoscaler) DeepCopyInto(out *EffectiveHorizontalPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveHorizontalPodAutoscaler.
func (in *EffectiveHorizontalPodAutoscaler) DeepCopy() *EffectiveHorizontalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(EffectiveHorizontalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EffectiveHorizontalPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveHorizontalPodAutoscalerList) DeepCopyInto(out *EffectiveHorizontalPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EffectiveHorizontalPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveHorizontalPodAutoscalerList.
func (in *EffectiveHorizontalPodAutoscalerList) DeepCopy() *EffectiveHorizontalPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(EffectiveHorizontalPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EffectiveHorizontalPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveHorizontalPodAutoscalerSpec) DeepCopyInto(out *EffectiveHorizontalPodAutoscalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.SpecificReplicas != nil {
		in, out := &in.SpecificReplicas, &out.SpecificReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2beta2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(v2beta2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Prediction != nil {
		in, out := &in.Prediction, &out.Prediction
		*out = new(Prediction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveHorizontalPodAutoscalerSpec.
func (in *EffectiveHorizontalPodAutoscalerSpec) DeepCopy() *EffectiveHorizontalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(EffectiveHorizontalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveHorizontalPodAutoscalerStatus) DeepCopyInto(out *EffectiveHorizontalPodAutoscalerStatus) {
	*out = *in
	if in.ExpectReplicas != nil {
		in, out := &in.ExpectReplicas, &out.ExpectReplicas
		*out = new(int32)
		**out = **in
	}
	if in.CurrentReplicas != nil {
		in, out := &in.CurrentReplicas, &out.CurrentReplicas
		*out = new(int32)
		**out = **in
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveHorizontalPodAutoscalerStatus.
func (in *EffectiveHorizontalPodAutoscalerStatus) DeepCopy() *EffectiveHorizontalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(EffectiveHorizontalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prediction) DeepCopyInto(out *Prediction) {
	*out = *in
	if in.PredictionWindowSeconds != nil {
		in, out := &in.PredictionWindowSeconds, &out.PredictionWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.PredictionAlgorithm != nil {
		in, out := &in.PredictionAlgorithm, &out.PredictionAlgorithm
		*out = new(PredictionAlgorithm)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prediction.
func (in *Prediction) DeepCopy() *Prediction {
	if in == nil {
		return nil
	}
	out := new(Prediction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionAlgorithm) DeepCopyInto(out *PredictionAlgorithm) {
	*out = *in
	if in.DSP != nil {
		in, out := &in.DSP, &out.DSP
		*out = new(predictionv1alpha1.DSP)
		(*in).DeepCopyInto(*out)
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = new(predictionv1alpha1.Percentile)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionAlgorithm.
func (in *PredictionAlgorithm) DeepCopy() *PredictionAlgorithm {
	if in == nil {
		return nil
	}
	out := new(PredictionAlgorithm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Substitute) DeepCopyInto(out *Substitute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Substitute.
func (in *Substitute) DeepCopy() *Substitute {
	if in == nil {
		return nil
	}
	out := new(Substitute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Substitute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstituteList) DeepCopyInto(out *SubstituteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Substitute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstituteList.
func (in *SubstituteList) DeepCopy() *SubstituteList {
	if in == nil {
		return nil
	}
	out := new(SubstituteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstituteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstituteSpec) DeepCopyInto(out *SubstituteSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.SubstituteTargetRef = in.SubstituteTargetRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstituteSpec.
func (in *SubstituteSpec) DeepCopy() *SubstituteSpec {
	if in == nil {
		return nil
	}
	out := new(SubstituteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstituteStatus) DeepCopyInto(out *SubstituteStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstituteStatus.
func (in *SubstituteStatus) DeepCopy() *SubstituteStatus {
	if in == nil {
		return nil
	}
	out := new(SubstituteStatus)
	in.DeepCopyInto(out)
	return out
}
