// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceAction) DeepCopyInto(out *AvoidanceAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceAction.
func (in *AvoidanceAction) DeepCopy() *AvoidanceAction {
	if in == nil {
		return nil
	}
	out := new(AvoidanceAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvoidanceAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionList) DeepCopyInto(out *AvoidanceActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvoidanceAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionList.
func (in *AvoidanceActionList) DeepCopy() *AvoidanceActionList {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvoidanceActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionSpec) DeepCopyInto(out *AvoidanceActionSpec) {
	*out = *in
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(ThrottleAction)
		**out = **in
	}
	if in.Eviction != nil {
		in, out := &in.Eviction, &out.Eviction
		*out = new(EvictionAction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionSpec.
func (in *AvoidanceActionSpec) DeepCopy() *AvoidanceActionSpec {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionStatus) DeepCopyInto(out *AvoidanceActionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionStatus.
func (in *AvoidanceActionStatus) DeepCopy() *AvoidanceActionStatus {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceStrategy) DeepCopyInto(out *AvoidanceStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceStrategy.
func (in *AvoidanceStrategy) DeepCopy() *AvoidanceStrategy {
	if in == nil {
		return nil
	}
	out := new(AvoidanceStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUThrottle) DeepCopyInto(out *CPUThrottle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUThrottle.
func (in *CPUThrottle) DeepCopy() *CPUThrottle {
	if in == nil {
		return nil
	}
	out := new(CPUThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionAction) DeepCopyInto(out *EvictionAction) {
	*out = *in
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionAction.
func (in *EvictionAction) DeepCopy() *EvictionAction {
	if in == nil {
		return nil
	}
	out := new(EvictionAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryThrottle) DeepCopyInto(out *MemoryThrottle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryThrottle.
func (in *MemoryThrottle) DeepCopy() *MemoryThrottle {
	if in == nil {
		return nil
	}
	out := new(MemoryThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricRule) DeepCopyInto(out *MetricRule) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Value = in.Value.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricRule.
func (in *MetricRule) DeepCopy() *MetricRule {
	if in == nil {
		return nil
	}
	out := new(MetricRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalGet) DeepCopyInto(out *NodeLocalGet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalGet.
func (in *NodeLocalGet) DeepCopy() *NodeLocalGet {
	if in == nil {
		return nil
	}
	out := new(NodeLocalGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicy) DeepCopyInto(out *NodeQOSEnsurancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicy.
func (in *NodeQOSEnsurancePolicy) DeepCopy() *NodeQOSEnsurancePolicy {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeQOSEnsurancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicyList) DeepCopyInto(out *NodeQOSEnsurancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeQOSEnsurancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicyList.
func (in *NodeQOSEnsurancePolicyList) DeepCopy() *NodeQOSEnsurancePolicyList {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeQOSEnsurancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicySpec) DeepCopyInto(out *NodeQOSEnsurancePolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.NodeQualityProbe.DeepCopyInto(&out.NodeQualityProbe)
	if in.ObjectiveEnsurances != nil {
		in, out := &in.ObjectiveEnsurances, &out.ObjectiveEnsurances
		*out = make([]ObjectiveEnsurance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicySpec.
func (in *NodeQOSEnsurancePolicySpec) DeepCopy() *NodeQOSEnsurancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicyStatus) DeepCopyInto(out *NodeQOSEnsurancePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicyStatus.
func (in *NodeQOSEnsurancePolicyStatus) DeepCopy() *NodeQOSEnsurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQualityProbe) DeepCopyInto(out *NodeQualityProbe) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(corev1.HTTPGetAction)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeLocalGet != nil {
		in, out := &in.NodeLocalGet, &out.NodeLocalGet
		*out = new(NodeLocalGet)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQualityProbe.
func (in *NodeQualityProbe) DeepCopy() *NodeQualityProbe {
	if in == nil {
		return nil
	}
	out := new(NodeQualityProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectiveEnsurance) DeepCopyInto(out *ObjectiveEnsurance) {
	*out = *in
	if in.MetricRule != nil {
		in, out := &in.MetricRule, &out.MetricRule
		*out = new(MetricRule)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectiveEnsurance.
func (in *ObjectiveEnsurance) DeepCopy() *ObjectiveEnsurance {
	if in == nil {
		return nil
	}
	out := new(ObjectiveEnsurance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicy) DeepCopyInto(out *PodQOSEnsurancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicy.
func (in *PodQOSEnsurancePolicy) DeepCopy() *PodQOSEnsurancePolicy {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodQOSEnsurancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicyList) DeepCopyInto(out *PodQOSEnsurancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodQOSEnsurancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicyList.
func (in *PodQOSEnsurancePolicyList) DeepCopy() *PodQOSEnsurancePolicyList {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodQOSEnsurancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicySpec) DeepCopyInto(out *PodQOSEnsurancePolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.QualityProbe.DeepCopyInto(&out.QualityProbe)
	if in.ObjectiveEnsurances != nil {
		in, out := &in.ObjectiveEnsurances, &out.ObjectiveEnsurances
		*out = make([]ObjectiveEnsurance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicySpec.
func (in *PodQOSEnsurancePolicySpec) DeepCopy() *PodQOSEnsurancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicyStatus) DeepCopyInto(out *PodQOSEnsurancePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicyStatus.
func (in *PodQOSEnsurancePolicyStatus) DeepCopy() *PodQOSEnsurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProbe) DeepCopyInto(out *QualityProbe) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(corev1.HTTPGetAction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProbe.
func (in *QualityProbe) DeepCopy() *QualityProbe {
	if in == nil {
		return nil
	}
	out := new(QualityProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMutation) DeepCopyInto(out *ResourceMutation) {
	*out = *in
	if in.RequestMutations != nil {
		in, out := &in.RequestMutations, &out.RequestMutations
		*out = make([]ResourcetMutation, len(*in))
		copy(*out, *in)
	}
	if in.LimitMutations != nil {
		in, out := &in.LimitMutations, &out.LimitMutations
		*out = make([]ResourcetMutation, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMutation.
func (in *ResourceMutation) DeepCopy() *ResourceMutation {
	if in == nil {
		return nil
	}
	out := new(ResourceMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePriority) DeepCopyInto(out *ResourcePriority) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePriority.
func (in *ResourcePriority) DeepCopy() *ResourcePriority {
	if in == nil {
		return nil
	}
	out := new(ResourcePriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcetMutation) DeepCopyInto(out *ResourcetMutation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcetMutation.
func (in *ResourcetMutation) DeepCopy() *ResourcetMutation {
	if in == nil {
		return nil
	}
	out := new(ResourcetMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicy) DeepCopyInto(out *ServicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicy.
func (in *ServicePolicy) DeepCopy() *ServicePolicy {
	if in == nil {
		return nil
	}
	out := new(ServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyList) DeepCopyInto(out *ServicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServicePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyList.
func (in *ServicePolicyList) DeepCopy() *ServicePolicyList {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicySpec) DeepCopyInto(out *ServicePolicySpec) {
	*out = *in
	out.ResourcePriority = in.ResourcePriority
	out.AvoidanceStrategy = in.AvoidanceStrategy
	in.ResourceMutation.DeepCopyInto(&out.ResourceMutation)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicySpec.
func (in *ServicePolicySpec) DeepCopy() *ServicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ServicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyStatus) DeepCopyInto(out *ServicePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyStatus.
func (in *ServicePolicyStatus) DeepCopy() *ServicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleAction) DeepCopyInto(out *ThrottleAction) {
	*out = *in
	out.CPUThrottle = in.CPUThrottle
	out.MemoryThrottle = in.MemoryThrottle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleAction.
func (in *ThrottleAction) DeepCopy() *ThrottleAction {
	if in == nil {
		return nil
	}
	out := new(ThrottleAction)
	in.DeepCopyInto(out)
	return out
}
